import db from '../db/index.js';
const dbs ={
  'link':{
    urlname:'/link',
    schema:db.LinkSchema,
    collectionname:'link',
  },
  'devicetype':{
    urlname:'/devicetype',
    schema:db.DevicetypeSchema,
    collectionname:'devicetype',
  },
  'cwithdrawcash':{
      urlname:'/cwithdrawcash',
      schema:db.CWithdrawcashapplySchema,
      collectionname:'cwithdrawcash',
  },
  'recommendhistory':{
     urlname:'/recommendhistory',
     schema:db.RecommendHistorySchema,
     collectionname:'recommendhistory',
  },
  'eshop':{
    urlname:'/eshop',
    schema:db.EShopSchema,
    collectionname:'eshop',
  },
  'cshop':{
    urlname:'/cshop',
    schema:db.CShopSchema,
    collectionname:'cshop',
  },
  'typeofwork':{
    urlname:'/typeofwork',
    schema:db.TypeofworkSchema,
    collectionname:'typeofwork',
  },
  'tag':{
    urlname:'/tag',
    schema:db.TagSchema,
    collectionname:'tag',
  },
  'addressconst':{
    urlname:'/addressconst',
    schema:db.AddressconstSchema,
    collectionname:'addressconst',
  },
  'postagetemplate':{
    urlname:'/postagetemplate',
    schema:db.PostageTemplateSchema,
    collectionname:'postagetemplate',
  },
  'about':{
    urlname:'/about',
    schema:db.AboutSchema,
    collectionname:'about',
  },
  'systemconfig':{
    urlname:'/systemconfig',
    schema:db.SystemConfigSchema,
    collectionname:'systemconfig',
  },
  'user':{
    urlname:'/user',
    schema:db.UserSchema,
    collectionname:'user',
  },
  'device':{
    urlname:'/device',
    schema:db.DeviceSchema,
    collectionname:'device',
  },
  'topic':{
    urlname:'/topic',
    schema:db.TopicSchema,
    collectionname:'topic',
  },
  'address':{
    urlname:'/address',
    schema:db.AddressSchema,
    collectionname:'address',
  },
  'comments':{
    urlname:'/comments',
    schema:db.CommentSchema,
    collectionname:'comments',
  },
  'notifymessage':{
    urlname:'/notifymessage',
    schema:db.NotifyMessageSchema,
    collectionname:'notifymessage',
  },
  'banner':{
    urlname:'/banner',
    schema:db.BannerSchema,
    collectionname:'banner',
  },
  'eproduct':{
    urlname:'/eproduct',
    schema:db.EProductSchema,
    collectionname:'eproduct',
  },
  'ecategory':{
    urlname:'/ecategory',
    schema:db.ECategorySchema,
    collectionname:'ecategory',
  },
  'cproduct':{
    urlname:'/cproduct',
    schema:db.CProductSchema,
    collectionname:'cproduct',
  },
   'order':{
    urlname:'/order',
    schema:db.OrderSchema,
    collectionname:'order',
  },
  'express':{
    urlname:'/express',
    schema:db.ExpressSchema,
    collectionname:'express',
  },
  'emycoupon':{
    urlname:'/emycoupon',
    schema:db.EMyCouponSchema,
    collectionname:'emycoupon',
  },
  'feedback':{
    urlname:'/feedback',
    schema:db.FeedbackSchema,
    collectionname:'feedback',
  },
  'news':{
    urlname:'/news',
    schema:db.NewsSchema,
    collectionname:'news',
  },
   'device':{
    urlname:'/device',
    schema:db.DeviceSchema,
    collectionname:'device',
  },
   'realtimedata':{
    urlname:'/realtimedata',
    schema:db.RealtimedataSchema,
    collectionname:'realtimedata',
  },
  'devicedatahistory':{
   urlname:'/devicedatahistory',
   schema:db.DeviceDataHistorySchema,
   collectionname:'devicedatahistory',
  },
};

export default dbs;
